image_width: 640
image_height: 480
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [542.75992,   0.     , 682.55209,
           0.     , 549.48474, 295.06407,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.224320, 0.030992, -0.001153, -0.001051, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [365.07574,   0.     , 665.86839,   0.     ,
           0.     , 473.31491, 273.49449,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]